### ISSUE TITLE
Rendering JSON

### ISSUE THREAD

**Issue by 1e4** [martinlindhe/php-tiled-tmx#1]
Hey Martin,

I was wondering if you ever did a package for displaying a map in PHP? I originally thought this package would do it, but it seems that it "only" turns it into JSON. 

Love how the package works so far, also your buy a coffee link doesn't work.

**Comment by 1e4** [comment]
I created a gist as an example of how to render this, my use case required tables, but can easily be changed. 

Thanks again for the package! :)

https://gist.github.com/1e4/3c31843e2370417d1823f809576fafbb

**Comment by martinlindhe** [comment]
Hi and thanks :-) The buymeacoffe site seems to have inactivated my account so I removed it from my profile.

I have moved on from php, but when I worked on this piece of code, I basically had a backend of php that used php-tiled-tmx to turn tiled maps from xml to json, using something like this:

```php
<?php namespace App\Console\Commands;

use Illuminate\Console\Command;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;

class BuildJsonMaps extends Command
{
    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'island:build-maps';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Build json maps from tmx source';

    /**
     * Execute the console command.
     *
     * Generates json map files from source .tmx (Tiled maps) in map directory
     *
     * @return mixed
     */
    public function fire()
    {
        $mapDir = base_path().'/resources/maps';

        $cacheDir = storage_path().'/map-cache';

        if (!is_dir($cacheDir)) {
            mkdir($cacheDir);
        }

        $files = glob($mapDir.'/*.{tmx}', GLOB_BRACE);

        foreach ($files as $file) {
            $tiled = new \TiledTmx\Parser();
            $map = $tiled->parseFile($file);

            $cacheFile = $cacheDir.'/'.substr(basename($file), 0, -4).'.json';

            echo realpath($file).' -> '.$cacheFile."\n";
            $data = \TiledTmx\JsonMapWriter::render($map);
            file_put_contents($cacheFile, $data);
        }
    }
}
```

Nowadays tiled editor allows to export directly to json.

Then I had a javascript game client that load that map and rendered it in browser.

Anyway, glad you found it useful!

**Comment by 1e4** [comment]
Oh that's pretty cool. I thought it did have export to JSON, but seems the linux build doesn't support it, which is what I'm on. I was pretty surprised this lib still worked given the age of the repo.

Thank you again for your work, very very helpful :+1:
